// 自动生成，如要添加站点请在config/api_sites.json中添加，并重新生成
import '../models/api_site.dart';

final List<ApiSite> apiSites = [
  ApiSite(
    key: 'heimuer',
    name: '黑木耳',
    api: 'https://json.heimuer.xyz',
    detail: 'https://heimuer.tv',
    adult: false,
  ),
  ApiSite(
    key: 'ffzy',
    name: '非凡影视',
    api: 'http://api.ffzyapi.com',
    detail: 'http://ffzy5.tv',
    adult: false,
  ),
  ApiSite(
    key: 'tyyszy',
    name: '天涯资源',
    api: 'https://tyyszy.com',
    detail: null,
    adult: false,
  ),
  ApiSite(
    key: 'ckzy',
    name: 'CK资源',
    api: 'https://www.ckzy1.com',
    detail: null,
    adult: true,
  ),
  ApiSite(
    key: 'zy360',
    name: '360资源',
    api: 'https://360zy.com',
    detail: null,
    adult: false,
  ),
  ApiSite(
    key: 'wolong',
    name: '卧龙资源',
    api: 'https://wolongzyw.com',
    detail: null,
    adult: false,
  ),
  ApiSite(
    key: 'cjhw',
    name: '新华为',
    api: 'https://cjhwba.com',
    detail: null,
    adult: false,
  ),
  ApiSite(
    key: 'hwba',
    name: '华为吧资源',
    api: 'https://cjwba.com',
    detail: null,
    adult: false,
  ),
  ApiSite(
    key: 'jisu',
    name: '极速资源',
    api: 'https://jszyapi.com',
    detail: 'https://jszyapi.com',
    adult: false,
  ),
  ApiSite(
    key: 'dbzy',
    name: '豆瓣资源',
    api: 'https://caiji.dbzy5.com',
    detail: 'https://dbzy.com',
    adult: false,
  ),
  ApiSite(
    key: 'bfzy',
    name: '暴风资源',
    api: 'https://bfzyapi.com',
    detail: null,
    adult: false,
  ),
  ApiSite(
    key: 'mozhua',
    name: '魔爪资源',
    api: 'https://mozhuazy.com',
    detail: null,
    adult: false,
  ),
  ApiSite(
    key: 'mdzy',
    name: '魔都资源',
    api: 'https://www.mdzyapi.com',
    detail: null,
    adult: false,
  ),
  ApiSite(
    key: 'ruyi',
    name: '如意资源',
    api: 'https://cj.rycjapi.com',
    detail: null,
    adult: false,
  ),
  ApiSite(
    key: 'jkun',
    name: 'jkun资源',
    api: 'https://jkunzyapi.com',
    detail: null,
    adult: true,
  ),
  ApiSite(
    key: 'bwzy',
    name: '百万资源',
    api: 'https://api.bwzym3u8.com',
    detail: null,
    adult: true,
  ),
  ApiSite(
    key: 'souav',
    name: 'souav资源',
    api: 'https://api.souavzy.vip',
    detail: null,
    adult: true,
  ),
  ApiSite(
    key: 'siwa',
    name: '丝袜资源',
    api: 'https://siwazyw.tv',
    detail: null,
    adult: true,
  ),
  ApiSite(
    key: 'r155',
    name: '155资源',
    api: 'https://155api.com',
    detail: null,
    adult: true,
  ),
  ApiSite(
    key: 'lsb',
    name: 'lsb资源',
    api: 'https://apilsbzy1.com',
    detail: null,
    adult: true,
  ),
  ApiSite(
    key: 'huangcang',
    name: '黄色仓库',
    api: 'https://hsckzy.vip',
    detail: 'https://hsckzy.vip',
    adult: true,
  ),
];
